# Generated by Django 2.2.6 on 2019-11-03 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('text', models.CharField(default='', max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to='authors.Author')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
