# Generated by Django 3.0 on 2019-12-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bibliography',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
