# Generated by Django 3.0 on 2020-01-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
        ('articles', '0003_article_bibliography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bibliography',
        ),
        migrations.AddField(
            model_name='article',
            name='bibliography',
            field=models.ManyToManyField(to='bibliography.Bibliography'),
        ),
    ]
