# Generated by Django 2.2.6 on 2019-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('articles', '0003_articlesresume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesresume',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='articlesresume',
            name='created',
        ),
        migrations.AddField(
            model_name='articlesresume',
            name='data',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AddField(
            model_name='articlesresume',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='articlesresume',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
