# Generated by Django 2.2.6 on 2019-11-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191103_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlesResume',
        ),
    ]
