# Generated by Django 3.0 on 2020-01-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('surname', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(default='', max_length=10000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
