# Generated by Django 2.2.6 on 2019-11-03 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/authors'),
            preserve_default=False,
        ),
    ]
