# Generated by Django 2.2.6 on 2019-11-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('articles', '0005_delete_articlesresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('articles', models.ManyToManyField(to='articles.Article')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
