# Generated by Django 3.0 on 2020-01-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('articles', models.ManyToManyField(blank=True, to='articles.Article')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
