# Generated by Django 3.0.3 on 2020-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('deviceId', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(default='', max_length=150)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
